BACKGROUND_COLOR = '#F0F0F0'
TEXT_COLOR = '#000000'
BUTTON_COLOR = '#4CAF50'
CLEAR_BUTTON_COLOR = '#FF5733'
OPERATOR_BUTTON_COLOR = '#FFC107'

FONT_SIZE = '30px'
BUTTON_FONT_WEIGHT = 'bold'
DISPLAY_FONT = 'Helvetica'